import type { Metadata } from "next";
import "./globals.css";
import "./globals.css";
import {  Calistoga, Inter} from "next/font/google";

const inter = Inter({ subsets: ["latin"], weight: ["200"], variable: "--font-sans" });
const calistoga = Calistoga({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${calistoga.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
